### PR TITLE
Using newest available version of chart.js library

### PR DESCRIPTION
**Pull request by fedemotta**

### CODE REVIEW

**Comment by creocoder** [comment]
@fedemotta We can't merge this, sorry. Its not safe to use `*` because extension done for specific version of library and we do not have garantee that future version will be compatible with that. All library updates should be investigated manually.

**Comment by fedemotta** [comment]
@creocoder It is fine to me because I am able to use my fork with this change. 

I opened this PR because I didn't have access to some feature developed in the chart.js library DEV branch. 

Should I wait until this feature is ready in a chart.js release and in a release of this extension?

It make no sense to me. This is just a wrapper of chart.js!

Anyway I think that you are misunderstanding the use of the DEV branch. You can still have fixed versions in your releases. I mean you can release a stable version with a specified version of the chart.js bower and then put again the \* in master.

I know that everyone is new to composer. Not totally sure how this is been handled by other projects but it make more sense this way. I am still looking the best way to handle this kind of issues in my own projects.

**Comment by creocoder** [comment]
> Anyway I think that you are misunderstanding the use of the DEV branch

The decision is absolutely consciously. Will give details below.

@fedemotta Its always bad idea to use `*` for versions, even for development version of widgets. There is much more agile tools inside composer for that, like `~` for library that use SemVer for example. We'll consider use `~` for master. We can't use `*` because we do not want potencial build fails inside README badges at least. Also extension is mainly designed for usage in production. For development version we'll consider use development branch.

**Comment by creocoder** [comment]
@fedemotta More information about why asterisk is **always bad idea**: https://igor.io/2013/01/07/composer-versioning.html

**Comment by fedemotta** [comment]
@creocoder

I'm still not totally convinced. I see that there are some PROS and CONS to go with asterisk in a DEV branch. I am using all the extensions with a specific version in my projects. But sometimes I need to move to the development version of some extension. For example this happens when I need to test some new feature to think ahead what to do with the next release of the extension. Also you are referencing the [ChartJs docs](http://www.chartjs.org/docs/) in your readme file. It could lead to some discrepancies if you keep a specific version and the main library uses another (it happens to me with a different yii extension not using bower at all).

Anyway I really appreciate your feedback and the article. I will further read about this. 

Thanks!

**Pull request closed without merging**
